name: Price Check

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Check prices via API
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/v1/products/check-prices \
          -H "Content-Type: application/json"
